builders:
  # name of the builder
  build_icon:
    import: "package:iconifyly/builder.dart"
    builder_factories: ["iconLibraryBuilder"]
    build_extensions: {".dart": [".icon.dart"]}
    build_to: source
    runs_before:
              - reflectable
          

targets:
  $default:
    builders:
      iconifyly|build_icon:
        generate_for:
            - lib/iconifyly.dart
        options:
          runs_before:
              - reflectable
      reflectable:
        generate_for:
          - lib/reflected.dart
          - lib/icons/*.dart
        options:
          formatted: true
          
      