// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'dart:ui' as prefix3;
import 'ic.icon.dart' as prefix1;
import 'package:flutter/src/widgets/framework.dart' as prefix2;
import 'package:iconifyly/reflected.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Ic',
            r'.Ic',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5],
            const <int>[6, 7, 8, 9, 10],
            const <int>[0, 1, 2, 3, 4],
            1,
            {
              r'info': () => prefix1.Ic.info,
              r'categories': () => prefix1.Ic.categories,
              r'aliases': () => prefix1.Ic.aliases,
              r'names': () => prefix1.Ic.names,
              r'getIcon': () => prefix1.Ic.getIcon
            },
            {},
            {r'': (bool b) => () => b ? prefix1.Ic() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'IconifylyInterface',
            r'.IconifylyInterface',
            134218247,
            1,
            const prefix0.Reflector(),
            const <int>[11, 12, 13, 14, 15, 16],
            const <int>[6, 7, 8, 9, 10],
            const <int>[11, 12, 13, 14, 15],
            -1,
            {
              r'info': () => prefix0.IconifylyInterface.info,
              r'categories': () => prefix0.IconifylyInterface.categories,
              r'aliases': () => prefix0.IconifylyInterface.aliases,
              r'names': () => prefix0.IconifylyInterface.names,
              r'Widget': () => prefix0.IconifylyInterface.Widget
            },
            {},
            {},
            1,
            1,
            const <int>[],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(r'info', 35651602, 0, -1, 2, 3, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'categories', 35651602, 0, -1, 2, 3, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'aliases', 35651602, 0, -1, 2, 3, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'names', 35651602, 0, -1, 4, 5, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'getIcon', 2097170, 0, -1, 6, 6, const <int>[],
            const <int>[0, 1, 2, 3, 4], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 7, 7, const <int>[],
            const <int>[5], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 8, 8, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1,
            const <int>[], const <int>[6], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 9, 9, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 10, 10,
            const <int>[], const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'info', 35651602, 1, -1, 2, 3, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'categories', 35651602, 1, -1, 2, 3, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'aliases', 35651602, 1, -1, 2, 3, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'names', 35651602, 1, -1, 4, 5, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'Widget', 524306, 1, -1, -1, -1, const <int>[],
            const <int>[7, 8, 9, 10, 11], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, const <int>[], const <int>[],
            const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'name', 134348806, 4, const prefix0.Reflector(),
            -1, 8, 8, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'height', 67252230, 4, const prefix0.Reflector(),
            -1, 11, 11, const <int>[], const [], null, #height),
        r.ParameterMirrorImpl(r'width', 67252230, 4, const prefix0.Reflector(),
            -1, 11, 11, const <int>[], const [], null, #width),
        r.ParameterMirrorImpl(r'rotate', 67252230, 4, const prefix0.Reflector(),
            -1, 11, 11, const <int>[], const [], null, #rotate),
        r.ParameterMirrorImpl(r'color', 67252230, 4, const prefix0.Reflector(),
            -1, 12, 12, const <int>[], const [], null, #color),
        r.ParameterMirrorImpl(r'other', 134348806, 6, const prefix0.Reflector(),
            -1, 13, 13, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            8,
            const prefix0.Reflector(),
            -1,
            14,
            14,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'name', 134348806, 15, const prefix0.Reflector(),
            -1, 8, 8, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'height',
            67252230,
            15,
            const prefix0.Reflector(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            #height),
        r.ParameterMirrorImpl(r'width', 67252230, 15, const prefix0.Reflector(),
            -1, 15, 15, const <int>[], const [], null, #width),
        r.ParameterMirrorImpl(
            r'rotate',
            67252230,
            15,
            const prefix0.Reflector(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            #rotate),
        r.ParameterMirrorImpl(r'color', 67252230, 15, const prefix0.Reflector(),
            -1, 12, 12, const <int>[], const [], null, #color)
      ],
      <Type>[
        prefix1.Ic,
        prefix0.IconifylyInterface,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        const m.TypeValue<Map<String, Map<String, dynamic>>>().type,
        Map,
        prefix2.Widget,
        bool,
        String,
        int,
        Type,
        double,
        prefix3.Color,
        Object,
        Invocation,
        num
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:iconifyly/icons/ic.icon.dart'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null),
        r.LibraryMirrorImpl(r'', Uri.parse('package:iconifyly/reflected.dart'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
